# Generated by Django 4.2 on 2023-05-07 00:28

from django.db import migrations, models
from django.utils import timezone


def set_sleep_nap_values(apps, schema_editor):
    # The live model is only used for its site settings (the nap bounds); rows
    # go through the historical model, which matches the table at this point
    # in the migration history.
    from core.models import Sleep as LiveSleep

    nap_start_min = LiveSleep.settings.nap_start_min
    nap_start_max = LiveSleep.settings.nap_start_max
    Sleep = apps.get_model("core", "Sleep")
    for sleep in Sleep.objects.all():
        sleep.nap = (
            nap_start_min <= timezone.localtime(sleep.start).time() <= nap_start_max
        )
        sleep.save(update_fields=["nap"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_alter_timer_options_remove_timer_duration_and_more"),
        ("dbsettings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sleep",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-start"],
                "permissions": [("can_edit_sleep_settings", "Can edit Sleep settings")],
                "verbose_name": "Sleep",
                "verbose_name_plural": "Sleep",
            },
        ),
        migrations.RemoveField(
            model_name="sleep",
            name="napping",
        ),
        migrations.AddField(
            model_name="sleep",
            name="nap",
            field=models.BooleanField(null=True, verbose_name="Nap"),
        ),
        migrations.RunPython(
            set_sleep_nap_values, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="sleep",
            name="nap",
            field=models.BooleanField(blank=True, verbose_name="Nap"),
        ),
    ]
