# Generated by Django 5.2.17 on 2026-09-20 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_tummytime_notes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bmi",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "BMI",
                "verbose_name_plural": "BMI",
            },
        ),
        migrations.AlterModelOptions(
            name="feeding",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-start"],
                "permissions": [
                    ("can_edit_feeding_settings", "Can edit Feeding settings")
                ],
                "verbose_name": "Feeding",
                "verbose_name_plural": "Feedings",
            },
        ),
        migrations.AlterModelOptions(
            name="headcircumference",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Head Circumference",
                "verbose_name_plural": "Head Circumference",
            },
        ),
        migrations.AlterModelOptions(
            name="height",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Height",
                "verbose_name_plural": "Height",
            },
        ),
        migrations.AlterModelOptions(
            name="weight",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-date", "-id"],
                "verbose_name": "Weight",
                "verbose_name_plural": "Weight",
            },
        ),
    ]
