# Generated by Django 5.2.17 on 2026-09-20 19:21

import csv

from django.db import migrations, models, transaction
from django.utils import dateparse


def add_to_orm(HeadCircumferencePercentile, alias, filepath, sex):
    """Load one WHO head-circumference-for-age expanded percentile table."""
    with open(filepath) as csvfile:
        rows = []
        for row in csv.DictReader(csvfile):
            rows.append(
                HeadCircumferencePercentile(
                    age_in_days=dateparse.parse_duration(f'P{row["Age"]}D'),
                    sex=sex,
                    p3_head_circumference=row["P3"],
                    p15_head_circumference=row["P15"],
                    p50_head_circumference=row["P50"],
                    p85_head_circumference=row["P85"],
                    p97_head_circumference=row["P97"],
                )
            )
        HeadCircumferencePercentile.objects.using(alias).bulk_create(
            rows, batch_size=50
        )


def insert_head_circumference_percentiles(apps, schema_editor):
    HeadCircumferencePercentile = apps.get_model("core", "HeadCircumferencePercentile")
    db_alias = schema_editor.connection.alias
    for sex, filename in (("boy", "boys"), ("girl", "girls")):
        with transaction.atomic():
            add_to_orm(
                HeadCircumferencePercentile,
                db_alias,
                f"core/migrations/head_circumference_percentile_{filename}.csv",
                sex,
            )


def remove_head_circumference_percentiles(apps, schema_editor):
    HeadCircumferencePercentile = apps.get_model("core", "HeadCircumferencePercentile")
    db_alias = schema_editor.connection.alias
    with transaction.atomic():
        HeadCircumferencePercentile.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_alter_weight_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pumping",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("left", "Left"), ("right", "Right"), ("both", "Both")],
                max_length=255,
                null=True,
                verbose_name="Side",
            ),
        ),
        migrations.CreateModel(
            name="HeadCircumferencePercentile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_in_days", models.DurationField()),
                ("p3_head_circumference", models.FloatField()),
                ("p15_head_circumference", models.FloatField()),
                ("p50_head_circumference", models.FloatField()),
                ("p85_head_circumference", models.FloatField()),
                ("p97_head_circumference", models.FloatField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("girl", "Girl"), ("boy", "Boy")], max_length=255
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("age_in_days", "sex"),
                        name="unique_age_sex_head_circumference",
                    )
                ],
            },
        ),
        migrations.RunPython(
            insert_head_circumference_percentiles,
            remove_head_circumference_percentiles,
        ),
    ]
