# Generated by Django 5.2.17 on 2026-09-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_pumping_side_head_circumference_percentiles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["last_name", "first_name"],
                "permissions": [("can_edit_child_settings", "Can edit Child settings")],
                "verbose_name": "Child",
                "verbose_name_plural": "Children",
            },
        ),
    ]
