# Generated by Django 5.2.17 on 2026-09-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_child_dashboard_settings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diaperchange",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-time"],
                "permissions": [
                    (
                        "can_edit_diaperchange_settings",
                        "Can edit Diaper Change settings",
                    )
                ],
                "verbose_name": "Diaper Change",
                "verbose_name_plural": "Diaper Changes",
            },
        ),
    ]
