# Generated by Django 5.2.17 on 2026-09-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_diaperchange_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="Optional. For a premature birth, growth percentiles and the corrected age count from this date.",
                null=True,
                verbose_name="Due date",
            ),
        ),
    ]
