# Generated by Django 5.2.17 on 2026-09-20 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_preferences_and_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="timer",
            name="paused_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Paused at"
            ),
        ),
        migrations.AddField(
            model_name="timer",
            name="paused_total",
            field=models.DurationField(
                default=datetime.timedelta, editable=False, verbose_name="Paused time"
            ),
        ),
    ]
