# Generated by Django 5.2.17 on 2026-09-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weight",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": [
                    "-date",
                    models.OrderBy(models.F("time"), descending=True, nulls_last=True),
                    "-id",
                ],
                "verbose_name": "Weight",
                "verbose_name_plural": "Weight",
            },
        ),
        migrations.AddField(
            model_name="weight",
            name="time",
            field=models.TimeField(
                blank=True,
                help_text="Optional, e.g. to tell several weigh-ins on one day apart.",
                null=True,
                verbose_name="Time",
            ),
        ),
    ]
