# Generated by Django 5.2.17 on 2026-09-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeding",
            name="last_breast",
            field=models.CharField(
                blank=True,
                choices=[("left", "Left"), ("right", "Right")],
                help_text='For "both breasts": the side the feeding ended on, so the next one can start on the other side.',
                max_length=255,
                null=True,
                verbose_name="Ended on",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="dashboard",
            field=models.BooleanField(
                default=False,
                help_text="Show the time since this tag was last used on each child's dashboard, e.g. for a medicine or a treatment.",
                verbose_name="Show on dashboard",
            ),
        ),
    ]
