# Generated by Django 5.2.17 on 2026-09-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_mixed_feedings_and_new_activities"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeding",
            name="entry_unit",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="Entry unit"
            ),
        ),
        migrations.AddField(
            model_name="headcircumference",
            name="entry_unit",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="Entry unit"
            ),
        ),
        migrations.AddField(
            model_name="height",
            name="entry_unit",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="Entry unit"
            ),
        ),
        migrations.AddField(
            model_name="pumping",
            name="entry_unit",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="Entry unit"
            ),
        ),
        migrations.AddField(
            model_name="temperature",
            name="entry_unit",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="Entry unit"
            ),
        ),
        migrations.AddField(
            model_name="weight",
            name="entry_unit",
            field=models.CharField(
                blank=True, default="", max_length=8, verbose_name="Entry unit"
            ),
        ),
    ]
