# Generated by Django 5.2.17 on 2026-09-21 06:03

import django.db.models.deletion
from django.db import migrations, models


def populate_bmi(apps, schema_editor):
    import math
    from collections import defaultdict
    from django.db.models import F

    Child, Weight, Height, BMI = [
        apps.get_model("core", name) for name in ("Child", "Weight", "Height", "BMI")
    ]
    using = schema_editor.connection.alias
    for child_id in Child.objects.using(using).values_list("pk", flat=True):
        days = defaultdict(dict)
        for row in (
            Weight.objects.using(using)
            .filter(child_id=child_id)
            .order_by("date", F("time").asc(nulls_first=True), "pk")
        ):
            days[row.date]["weight"] = row
        for row in (
            Height.objects.using(using).filter(child_id=child_id).order_by("date", "pk")
        ):
            days[row.date]["height"] = row
        weight = height = None
        entries = []
        for date, rows in sorted(days.items()):
            weight, height = rows.get("weight", weight), rows.get("height", height)
            if (
                not weight
                or not height
                or weight.entry_unit not in {"kg", "lb", "oz"}
                or height.entry_unit not in {"cm", "in"}
            ):
                continue
            try:
                value = weight.weight / (height.height / 100) ** 2
            except (ZeroDivisionError, OverflowError):
                continue
            if (
                weight.weight > 0
                and height.height > 0
                and math.isfinite(value)
                and math.isfinite(height.height)
            ):
                entries.append(
                    BMI(
                        child_id=child_id,
                        date=date,
                        bmi=value,
                        is_calculated=True,
                        source_weight_id=weight.pk,
                        source_height_id=height.pk,
                    )
                )
        BMI.objects.using(using).bulk_create(entries)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_feeding_entry_unit_headcircumference_entry_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmi",
            name="source_height",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.height",
            ),
        ),
        migrations.AddField(
            model_name="bmi",
            name="source_weight",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.weight",
            ),
        ),
        migrations.AddField(
            model_name="bmi",
            name="is_calculated",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(populate_bmi, migrations.RunPython.noop),
    ]
