# Generated by Django 5.2.17 on 2026-09-22 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_automatic_bmi_sources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pumping",
            name="child",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pumping",
                to="core.child",
                verbose_name="Child",
            ),
        ),
    ]
