# Generated by Django 5.2.17 on 2026-09-22 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_alter_pumping_child"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="diaperchange",
            index=models.Index(fields=["child", "time"], name="diaper_child_time_idx"),
        ),
    ]
