# Generated by Django 5.2.17 on 2026-09-22 17:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_diaperchange_diaper_child_time_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "track_duration",
                    models.BooleanField(default=False, verbose_name="Track duration"),
                ),
                (
                    "amount_label",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Number field label"
                    ),
                ),
                (
                    "amount_unit",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Number unit"
                    ),
                ),
                (
                    "choice_label",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Dropdown label"
                    ),
                ),
                (
                    "choice_options",
                    models.TextField(
                        blank=True, verbose_name="Dropdown options (one per line)"
                    ),
                ),
                (
                    "check_label",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Yes/no field label"
                    ),
                ),
                (
                    "text_label",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="Text field label"
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="timer",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="CustomActivity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(default=django.utils.timezone.now)),
                ("end", models.DateTimeField(default=django.utils.timezone.now)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("choice", models.CharField(blank=True, max_length=120)),
                ("checked", models.BooleanField(default=False)),
                ("text", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                (
                    "activity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.activitytype",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_activities",
                        to="core.child",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added by",
                    ),
                ),
            ],
            options={
                "ordering": ["-start", "-pk"],
            },
        ),
    ]
