# Generated by Django 5.2.17 on 2026-09-22 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_activitytype_timer_context_customactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="feeding",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="foods",
                to="core.feeding",
                verbose_name="Feeding",
            ),
        ),
    ]
