# Generated by Django 5.2.17 on 2026-09-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_food_feeding"),
    ]

    operations = [
        migrations.AddField(
            model_name="pumping",
            name="left_amount",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Left breast amount"
            ),
        ),
        migrations.AddField(
            model_name="pumping",
            name="right_amount",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Right breast amount"
            ),
        ),
        migrations.AlterField(
            model_name="feeding",
            name="method",
            field=models.CharField(
                choices=[
                    ("bottle", "Bottle"),
                    ("left breast", "Left breast"),
                    ("right breast", "Right breast"),
                    ("both breasts", "Both breasts"),
                    ("parent fed", "Caregiver fed"),
                    ("self fed", "Self fed"),
                ],
                max_length=255,
                verbose_name="Method",
            ),
        ),
    ]
