# Generated by Django 5.2.17 on 2026-09-23 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_pumping_left_amount_pumping_right_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feeding",
            name="method",
            field=models.CharField(
                choices=[
                    ("bottle", "Bottle"),
                    ("tube", "Tube"),
                    ("left breast", "Left breast"),
                    ("right breast", "Right breast"),
                    ("both breasts", "Both breasts"),
                    ("parent fed", "Caregiver fed"),
                    ("self fed", "Self fed"),
                ],
                max_length=255,
                verbose_name="Method",
            ),
        ),
    ]
