# Generated by Django 5.2.17 on 2026-09-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_deletionbatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="feeding",
            name="top_up_amount",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Top-up amount"
            ),
        ),
        migrations.AddField(
            model_name="feeding",
            name="top_up_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Top-up bottle time"
            ),
        ),
        migrations.AddField(
            model_name="feeding",
            name="top_up_secondary_amount",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Top-up second amount"
            ),
        ),
        migrations.AddField(
            model_name="feeding",
            name="top_up_secondary_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("breast milk", "Breast milk"),
                    ("formula", "Formula"),
                    ("fortified breast milk", "Fortified breast milk"),
                ],
                default="",
                max_length=255,
                verbose_name="Top-up second milk type",
            ),
        ),
        migrations.AddField(
            model_name="feeding",
            name="top_up_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("breast milk", "Breast milk"),
                    ("formula", "Formula"),
                    ("fortified breast milk", "Fortified breast milk"),
                ],
                default="",
                max_length=255,
                verbose_name="Top-up milk type",
            ),
        ),
    ]
