# Generated by Django 5.2.17 on 2026-09-20 07:40

import babybuddy.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0036_settings_access_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="language",
            field=models.CharField(
                choices=[
                    ("pt-BR", "Brazilian Portuguese"),
                    ("ca", "Catalan"),
                    ("hr", "Croatian"),
                    ("cs", "Czech"),
                    ("zh-hans", "Chinese (simplified)"),
                    ("zh-hant", "Chinese (traditional)"),
                    ("zh-tw", "Chinese (Taiwan)"),
                    ("da", "Danish"),
                    ("nl", "Dutch"),
                    ("en-US", "English (US)"),
                    ("en-GB", "English (UK)"),
                    ("fr", "French"),
                    ("fi", "Finnish"),
                    ("de", "German"),
                    ("he", "Hebrew"),
                    ("hu", "Hungarian"),
                    ("it", "Italian"),
                    ("ko", "Korean"),
                    ("ja", "Japanese"),
                    ("nb", "Norwegian Bokmål"),
                    ("pl", "Polish"),
                    ("pt", "Portuguese"),
                    ("ru", "Russian"),
                    ("sr", "Serbian"),
                    ("es", "Spanish"),
                    ("sv", "Swedish"),
                    ("tr", "Turkish"),
                    ("uk", "Ukrainian"),
                ],
                default="en-US",
                max_length=255,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="timezone",
            field=models.CharField(
                default=django.utils.timezone.get_default_timezone_name,
                max_length=100,
                validators=[babybuddy.models.validate_timezone],
                verbose_name="Timezone",
            ),
        ),
    ]
