# Generated by Django 5.2.17 on 2026-09-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0037_settings_timezone_runtime_validation"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="theme",
            field=models.CharField(
                choices=[
                    ("auto", "Match device"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                ],
                default="dark",
                max_length=255,
                verbose_name="Theme",
            ),
        ),
    ]
