# Generated by Django 5.2.17 on 2026-09-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0038_settings_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="dashboard_hidden_cards",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Hidden dashboard cards"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="timezone_follow_device",
            field=models.BooleanField(
                default=False,
                help_text="Follow the time zone of the browser or phone in use, e.g. while travelling, instead of the fixed time zone above.",
                verbose_name="Use the device's time zone",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="use_24_hour_time",
            field=models.BooleanField(
                default=False,
                help_text="Show times as 13:05 instead of 1:05 p.m.",
                verbose_name="24-hour clock",
            ),
        ),
    ]
