# Generated by Django 5.2.17 on 2026-09-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0039_preferences_and_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="measurement_system",
            field=models.CharField(
                choices=[
                    ("metric", "Metric (cm, kg, mL, °C)"),
                    ("us", "US customary (in, lbs, fl oz, °F)"),
                ],
                default="metric",
                max_length=10,
                verbose_name="Preferred units",
            ),
        ),
    ]
