# Generated by Django 5.2.17 on 2026-09-21 02:02

from django.db import migrations, models


def preserve_unit_preferences(apps, schema_editor):
    settings = apps.get_model("babybuddy", "Settings")
    settings.objects.using(schema_editor.connection.alias).filter(
        measurement_system="us"
    ).update(
        length_unit="in", liquid_unit="fl oz", weight_unit="lb", temperature_unit="F"
    )


def restore_unit_system(apps, schema_editor):
    settings = apps.get_model("babybuddy", "Settings")
    settings.objects.using(schema_editor.connection.alias).filter(
        length_unit="in", liquid_unit="fl oz", weight_unit="lb", temperature_unit="F"
    ).update(measurement_system="us")


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0040_settings_measurement_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="length_unit",
            field=models.CharField(
                choices=[("cm", "cm"), ("in", "in")],
                default="cm",
                max_length=10,
                verbose_name="Length",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="liquid_unit",
            field=models.CharField(
                choices=[("mL", "mL"), ("fl oz", "fl oz (US)")],
                default="mL",
                max_length=10,
                verbose_name="Liquid",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="temperature_unit",
            field=models.CharField(
                choices=[("C", "°C"), ("F", "°F")],
                default="C",
                max_length=10,
                verbose_name="Temperature",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="weight_unit",
            field=models.CharField(
                choices=[("kg", "kg"), ("lb", "lbs"), ("oz", "oz")],
                default="kg",
                max_length=10,
                verbose_name="Weight",
            ),
        ),
        migrations.RunPython(preserve_unit_preferences, restore_unit_system),
        migrations.RemoveField(
            model_name="settings",
            name="measurement_system",
        ),
    ]
