# Generated by Django 5.2.17 on 2026-09-21 06:05

import babybuddy.models
from django.db import migrations, models


def simplify_defaults(apps, schema_editor):
    hidden = [
        "pumping_last",
        "medication_last",
        "sleep_naps_day",
        "tummytime_day",
        "feeding_recent",
        "feeding_last_method",
        "sleep_recent",
        "pumping_recent",
        "statistics",
        "diaperchange_types",
        "breastfeeding",
        "notes_recent",
        "tags_last",
        "bathtime_last",
        "reflux_last",
        "food_recent",
        "measurement_head_circumference",
        "measurement_bmi",
        "measurement_temperature",
    ]
    Settings = apps.get_model("babybuddy", "Settings")
    for row in Settings.objects.using(schema_editor.connection.alias).all():
        row.dashboard_hidden_cards = (
            (list(row.dashboard_hidden_cards) + hidden[-3:])
            if row.dashboard_hidden_cards
            else hidden
        )
        row.save(update_fields=["dashboard_hidden_cards"])


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0041_independent_unit_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="dashboard_hidden_cards",
            field=models.JSONField(
                blank=True,
                default=babybuddy.models.default_hidden_dashboard_cards,
                verbose_name="Hidden dashboard cards",
            ),
        ),
        migrations.RunPython(simplify_defaults, migrations.RunPython.noop),
    ]
