# Generated by Django 5.2.17 on 2026-09-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0042_essential_dashboard_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="dashboard_card_order",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
