# Generated by Django 5.2.17 on 2026-09-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0043_dashboard_panel_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="pumping_reminder_basis",
            field=models.CharField(
                choices=[
                    ("combined", "Pumping or nursing"),
                    ("pumping", "Pumping only"),
                ],
                default="combined",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="pumping_reminder_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
