# Generated by Django 5.2.17 on 2026-09-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babybuddy", "0044_settings_pumping_reminder_basis_and_more"),
        ("core", "0054_activitytype_timer_context_customactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="allowed_children",
            field=models.ManyToManyField(
                blank=True, related_name="authorized_settings", to="core.child"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="hidden_activities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="settings",
            name="hidden_entry_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="settings",
            name="restrict_children",
            field=models.BooleanField(default=False),
        ),
    ]
