# Generated by Django 5.2.17 on 2026-09-21 20:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0051_automatic_bmi_sources"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildSupplyProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diaper_size", models.CharField(blank=True, max_length=40)),
                ("clothing_size", models.CharField(blank=True, max_length=40)),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supply_profile",
                        to="core.child",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("diapers", "Diapers"),
                            ("wipes", "Wipes"),
                            ("feeding", "Feeding supplies"),
                            ("formula", "Formula"),
                            ("food", "Food"),
                            ("clothing", "Clothing"),
                            ("bath", "Bath & skin care"),
                            ("health", "Health supplies"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=40)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("current", "Use now"),
                            ("next", "Next size / later"),
                            ("outgrown", "Outgrown / no longer used"),
                        ],
                        default="current",
                        max_length=12,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("items", "items"),
                            ("diapers", "diapers"),
                            ("wipes", "wipes"),
                            ("packs", "packs"),
                            ("cans", "cans"),
                            ("bottles", "bottles"),
                            ("mL", "mL"),
                            ("fl oz", "fl oz"),
                            ("g", "g"),
                            ("oz", "oz"),
                        ],
                        default="items",
                        max_length=12,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "low_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Remind at or below",
                    ),
                ),
                (
                    "target_stock",
                    models.DecimalField(
                        decimal_places=3,
                        default=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Restock up to",
                    ),
                ),
                (
                    "daily_use",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.001"))
                        ],
                        verbose_name="Estimated use per day",
                    ),
                ),
                (
                    "reminder_days",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="Days of notice"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Batch expiration"
                    ),
                ),
                (
                    "min_age_months",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Minimum age (months)"
                    ),
                ),
                (
                    "max_age_months",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Maximum age (months)"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("archived", models.BooleanField(default=False)),
                ("snoozed_until", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "child",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplies",
                        to="core.child",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add", "Restocked"),
                            ("use", "Used"),
                            ("set", "Count corrected"),
                        ],
                        max_length=10,
                    ),
                ),
                ("change", models.DecimalField(decimal_places=3, max_digits=12)),
                ("balance", models.DecimalField(decimal_places=3, max_digits=12)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.CharField(blank=True, max_length=160)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.stockitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="stock_nonnegative"
            ),
        ),
    ]
