# Generated by Django 5.2.17 on 2026-09-21 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_automatic_bmi_sources"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="childsupplyprofile",
            name="auto_deduct_diapers",
            field=models.BooleanField(
                default=True, verbose_name="Deduct diapers automatically"
            ),
        ),
        migrations.AddField(
            model_name="childsupplyprofile",
            name="diaper_stock",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diaper_users",
                to="inventory.stockitem",
                verbose_name="Diaper supply",
            ),
        ),
        migrations.CreateModel(
            name="DiaperStockUsage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("child_id_at_save", models.PositiveIntegerField()),
                ("deducted", models.BooleanField(default=False)),
                ("status", models.CharField(max_length=20)),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_usage",
                        to="core.diaperchange",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diaper_usages",
                        to="inventory.stockitem",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
