# Generated by Django 5.2.17 on 2026-09-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_childsupplyprofile_auto_deduct_diapers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockitem",
            name="child",
        ),
    ]
