# Generated by Django 5.2.17 on 2026-09-22 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_remove_stockitem_child"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockitem",
            name="daily_use",
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="low_stock",
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="reminder_days",
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="target_stock",
        ),
    ]
