# Generated by Django 5.2.17 on 2026-09-22 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_stockitem_daily_use_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["item", "action", "created_at"], name="stock_usage_time_idx"
            ),
        ),
    ]
