# Generated by Django 5.2.17 on 2026-09-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_activitytype_timer_context_customactivity"),
        ("inventory", "0005_stockmovement_stock_usage_time_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "weight_limit",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Maximum weight"
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("kg", "kg"), ("lb", "lbs"), ("oz", "oz")],
                        default="lb",
                        max_length=4,
                    ),
                ),
                (
                    "height_limit",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Maximum height"
                    ),
                ),
                (
                    "height_unit",
                    models.CharField(
                        choices=[("cm", "cm"), ("in", "in")], default="in", max_length=4
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, verbose_name="Other manufacturer limits"
                    ),
                ),
                (
                    "manual_review",
                    models.BooleanField(
                        default=False,
                        verbose_name="Needs review (milestone or other limit)",
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "children",
                    models.ManyToManyField(related_name="equipment", to="core.child"),
                ),
            ],
            options={
                "verbose_name_plural": "equipment",
                "ordering": ["name", "pk"],
            },
        ),
    ]
