"""Refresh hashes for reviewed exact runtime pins, or check the installed runtime.

requirements.txt is the reviewed version list; requirements.lock is the verified
pip installation input. Refresh never chooses newer versions or installs packages.
"""

import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
from importlib.metadata import version, PackageNotFoundError
import json
from pathlib import Path
import re
import urllib.request
from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "requirements.txt"
LOCK = ROOT / "requirements.lock"


def pins():
    result = []
    for line in SOURCE.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith(("#", "-")):
            continue
        requirement = Requirement(line)
        specs = list(requirement.specifier)
        if (
            len(specs) != 1
            or specs[0].operator != "=="
            or "*" in specs[0].version
            or requirement.url
        ):
            raise ValueError(
                "Every runtime requirement must have one exact version: " + line
            )
        result.append((line, requirement, specs[0].version))
    return result


def release_hashes(pin):
    line, requirement, release = pin
    request = urllib.request.Request(
        f"https://pypi.org/pypi/{canonicalize_name(requirement.name)}/{release}/json",
        headers={"User-Agent": "BabyBuddy-dependency-lock"},
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        metadata = json.load(response)
    hashes = sorted(
        {
            item["digests"]["sha256"]
            for item in metadata["urls"]
            if not item.get("yanked")
        }
    )
    if not hashes or any(not re.fullmatch(r"[0-9a-f]{64}", value) for value in hashes):
        raise ValueError("No valid, unyanked release hashes for " + requirement.name)
    return (
        line + " \\\n" + " \\\n".join("    --hash=sha256:" + value for value in hashes)
    )


def check():
    text = LOCK.read_text(encoding="utf-8")
    digest = hashlib.sha256(
        SOURCE.read_text(encoding="utf-8").encode("utf-8")
    ).hexdigest()
    if "# requirements.txt sha256: " + digest not in text:
        raise ValueError(
            "Runtime pins changed. Review them and refresh requirements.lock."
        )
    for line, requirement, release in pins():
        if line + " \\\n" not in text:
            raise ValueError("Missing locked requirement: " + line)
        if requirement.marker and not requirement.marker.evaluate():
            continue
        try:
            installed = version(requirement.name)
        except PackageNotFoundError:
            installed = "not installed"
        if installed != release:
            raise ValueError(
                f"{requirement.name}: expected {release}, found {installed}"
            )
    print("Runtime versions match the reviewed lock.")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refresh", action="store_true")
    args = parser.parse_args()
    if args.refresh:
        with ThreadPoolExecutor(max_workers=4) as pool:
            rows = list(pool.map(release_hashes, pins()))
        digest = hashlib.sha256(
            SOURCE.read_text(encoding="utf-8").encode("utf-8")
        ).hexdigest()
        content = (
            "# Generated by scripts/lock_requirements.py --refresh; do not edit.\n# requirements.txt sha256: "
            + digest
            + "\n--index-url https://pypi.org/simple\n--require-hashes\n\n"
            + "\n\n".join(rows)
            + "\n"
        )
        LOCK.write_text(content, encoding="utf-8", newline="\n")
        print(f"Locked {len(rows)} exact runtime requirements with release hashes.")
    else:
        check()


if __name__ == "__main__":
    main()
